### ISSUE TITLE
Assignment 2

### ISSUE THREAD

**Issue by jisaacks** [tiy-tpa-js-q1-2015/assignments#14]
https://github.com/tiy-tpa-js-q1-2015/assignments/tree/master/002#012715

**Comment by ktrammell95** [comment]
Ok I did as much as I could think to do and even started in CSS just because it made it easier for me to think through by going at that part right away. I am sure there are things I missed or there might be a better way to do them so I am looking forward to your feedback.

https://github.com/ktrammell95/tiy-assignment-2

**Comment by jisaacks** [comment]
@ktrammell95 you did great! Bravo!

My only feedback would be to look at your stylesheet. There are a lot of duplicate styles there. for example the **.interests** and the **.favorites** style blocks are exactly the same. How could you [**_DRY**_](http://en.wikipedia.org/wiki/Don%27t_repeat_yourself) that up?

**Comment by ktrammell95** [comment]
Ok I looked at it again and put them both in the same class name since they were the same stylings.  Is there more I could do or would that be about it?

**Comment by jisaacks** [comment]
@ktrammell95 if you wanted to keep them named differently you could have dry'ed up the css like this:

``` css
.interests, .favorites {
    background: #e6e9ec;
    padding: 10px; 
    border-radius: 4px; 
    display: inline-block; 
    margin: 5px;
    vertical-align: top;
    height: 150px;
}
```

Either way is valid.
