### ISSUE TITLE
Assignment 1

### ISSUE THREAD

**Issue by jisaacks** [tiy-tpa-js-q1-2015/assignments#5]
https://github.com/tiy-tpa-js-q1-2015/assignments/tree/master/001#012615

**Comment by mewilkerson** [comment]
http://codepen.io/mewilkerson/pen/dPRaaL?editors=110

**Comment by jisaacks** [comment]
Hi Matt! Overall this satisfies the requirements. Your HTML is valid, but you have some issues in your CSS. in the below snippet from your homework:

``` css
header {  

  background-image: url("https://urbanitesocialites.files.wordpress.com/2010/06/medium-wood-horizontal-background.jpg?w=1200");
  background-color: #cccac1;
  height: 500p;
  padding: 10px;
  border-bottom: 1px solid black;
  font-family: 

}
```

You specify a `font-family` with no value. Also please be sure to end all of your values with a semicolon.

---

Next time You may also want to spend a little effort on making it a little more easier to read. For example, the black text **Sunday, Sunday, Sunday** on the dark brown background is hard to read. It would be better with a lighter colored font. 

Also there is no consistent alignment to your page. Your titles, links, tables, etc. all appear to have different distances from the left of the page. This makes the site look jumbled.

I don't want you to feel bad though, It's very hard to get these things right. Overral you did a great job. Keep it up! :+1:
